In [9]:
import numpy as np
import pandas as pd
from keras.layers import Dense, Activation
from keras.models import Sequential

alcohols_raw = pd.read_excel('./ex_exercise.xlsx', header=1)

alcohols = alcohols.iloc[:, :9]

In [10]:
alcohols

,Cultivar,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39
...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56

In [11]:
def sigmoid(x):
    return 1/(1+np.exp(-x))